[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "duckdb>=1.2.2",
    "pandas>=2.0.3",
    "plotnine>=0.12.4",
    "requests>=2.32.3",
]
